language: node_js
node_js:
    - stable
before_install:
    - sudo apt-get install -y pv
before_script:
    - npm install
    - node index.js > sql/import.sql
script:
    - mysql -e 'CREATE DATABASE app;'
    - mysql < sql/createUTF8.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
    - mysql < sql/drop.sql
    - mysql < sql/createUTF8mb4.sql
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
